

branches:
  only:
    - master

skip_tags: true

skip_branch_with_pr: true



version: 1.29-appveyor{build}



image: Visual Studio 2019

clone_depth: 2500

cache:
  - build\externals

install:
  - build\download_externals.cmd auto



before_build:
  - build\auto\appveyor_set_version.cmd

build_script:
  - build\auto\build_openmpt_args.cmd vs2019 default Win32 Release 7z default
  - build\auto\build_openmpt_args.cmd vs2019 default x64   Release 7z default

after_build:
  - build\auto\package_openmpt_args.cmd vs2019 default Win32 Release 7z default
  - build\auto\package_openmpt_args.cmd vs2019 default x64   Release 7z default
  - build\auto\build_openmpt_release_packages_no_examples.cmd auto
  - build\auto\package_openmpt_installer_args.cmd vs2019 default Win32 Release 7z default
  - appveyor PushArtifact bin\openmpt-win32.tar
  - appveyor PushArtifact bin\openmpt-win64.tar
  - appveyor PushArtifact bin\openmpt-pkg.win.tar



test: off

