
language: c++

dist: trusty
sudo: required

env:
  global:
    - MAKEFLAGS="-j 2"
    - CCACHE_CPP2=1

matrix:
  fast_finish: true
  include:
    - os: linux
    - os: osx

before_install:
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y zip unzip p7zip xz-utils make binutils gcc g++ clang tcc pkg-config help2man doxygen autoconf autoconf-archive automake libtool ccache zlib1g-dev libmpg123-dev libogg-dev libvorbis-dev libportaudio-dev libpulse-dev libflac-dev libsndfile1-dev libltdl-dev ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install p7zip xz help2man doxygen autoconf-archive mpg123 libogg libvorbis portaudio flac libsndfile ; fi

install:
  - true

script:
  - ./build/auto/dist.sh

