name: FreeBSD Autotools

on:
  push:
    branches: [ OpenMPT-1.32 ]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        include:
          - { version: '15.0' }
          - { version: '14.3' }
          - { version: '13.5' }

    concurrency:
      group: ${{github.ref}}-${{github.workflow}}-${{matrix.version}}-autotools
      cancel-in-progress: true

    runs-on: ubuntu-24.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Startup VM
      uses: cross-platform-actions/action@bc98a4c4e12be618f9c276e5ff8562e20e1b38eb
      with:
        architecture: x86_64
        memory: 4G
        operating_system: freebsd
        version: ${{matrix.version}}
        shell: bash
        sync_files: runner-to-vm
        shutdown_vm: false
        run: true
    - name: Install dependencies
      uses: cross-platform-actions/action@bc98a4c4e12be618f9c276e5ff8562e20e1b38eb
      with:
        architecture: x86_64
        memory: 4G
        operating_system: freebsd
        version: ${{matrix.version}}
        shell: bash
        sync_files: false
        shutdown_vm: false
        run: |
          sudo pkg upgrade -y
          sudo pkg install -y subversion p5-XML-XPath git mawk gmake pkgconf autoconf autoconf-archive automake libtool help2man doxygen mpg123 libogg libvorbis flac libsndfile pulseaudio portaudio sdl2
    - name: Build
      uses: cross-platform-actions/action@bc98a4c4e12be618f9c276e5ff8562e20e1b38eb
      with:
        architecture: x86_64
        memory: 4G
        operating_system: freebsd
        version: ${{matrix.version}}
        shell: bash
        sync_files: false
        shutdown_vm: false
        run: |
          export MAKEFLAGS="-j$(sysctl -n hw.ncpu)"; ./build/autotools/autoconfiscate.sh
    - name: Shutdown VM
      uses: cross-platform-actions/action@bc98a4c4e12be618f9c276e5ff8562e20e1b38eb
      with:
        architecture: x86_64
        memory: 4G
        operating_system: freebsd
        version: ${{matrix.version}}
        shell: bash
        sync_files: false
        shutdown_vm: true
        run: true
