name: NetBSD 9.3 Makefile

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v4
    - uses: cross-platform-actions/action@v0.21.1
      with:
        architecture: x86_64
        hypervisor: qemu
        memory: 4G
        operating_system: netbsd
        version: '9.3'
        sync_files: runner-to-vm
        shell: bash
        run: |
          sudo pkgin -y install subversion git p5-XML-XPath mawk
          sudo pkgin -y install gmake pkgconf
          sudo pkgin -y install mpg123 libogg libvorbis flac libsndfile pulseaudio portaudio SDL2
          sudo pkgin -y install gcc7-libs   # for libstdc++7
          sudo pkgin -y install autoconf autoconf-archive automake libtool libltdl
          sudo pkgin -y install help2man
          #sudo pkgin -y install doxygen   # broken
          gmake -j4 STRICT=1 VERBOSE=1 AUTO_DEPS=1
          gmake -j4 STRICT=1 VERBOSE=1 AUTO_DEPS=1 check
