name: NetBSD 9.2 Makefile

on:
  push:
    branches: [ OpenMPT-1.31 ]
  pull_request:
    branches: [ OpenMPT-1.31 ]

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
    - uses: cross-platform-actions/action@v0.11.0
      with:
        architecture: x86_64
        hypervisor: qemu
        operating_system: netbsd
        version: '9.2'
        shell: bash
        run: |
          sudo pkgin -y install subversion git p5-XML-XPath mawk
          sudo pkgin -y install gmake pkgconf
          sudo pkgin -y install mpg123 libogg libvorbis flac libsndfile pulseaudio portaudio SDL2
          sudo pkgin -y install gcc7-libs   # for libstdc++7
          sudo pkgin -y install autoconf autoconf-archive automake libtool libltdl
          sudo pkgin -y install help2man
          #sudo pkgin -y install doxygen   # broken
          gmake -j$(sysctl -n hw.ncpu) STRICT=1 VERBOSE=1 AUTO_DEPS=1
          gmake -j$(sysctl -n hw.ncpu) STRICT=1 VERBOSE=1 AUTO_DEPS=1 check
