name: OpenBSD 7.4 Makefile

on:
  push:
    branches: [ OpenMPT-1.30 ]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: macos-12

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Startup VM
      uses: cross-platform-actions/action@v0.22.0
      with:
        architecture: x86_64
        hypervisor: xhyve
        memory: 4G
        operating_system: openbsd
        version: '7.4'
        shell: bash
        sync_files: runner-to-vm
        shutdown_vm: false
        run: true
    - name: Install dependencies
      uses: cross-platform-actions/action@v0.22.0
      with:
        architecture: x86_64
        hypervisor: xhyve
        memory: 4G
        operating_system: openbsd
        version: '7.4'
        shell: bash
        sync_files: false
        shutdown_vm: false
        run: |
          sudo pkg_add subversion p5-XML-XPath git mawk gmake pkgconf autoconf autoconf-archive automake libtool libltdl help2man doxygen mpg123 libogg libvorbis flac libsndfile pulseaudio portaudio-svn sdl2
    - name: Build
      uses: cross-platform-actions/action@v0.22.0
      with:
        architecture: x86_64
        hypervisor: xhyve
        memory: 4G
        operating_system: openbsd
        version: '7.4'
        shell: bash
        sync_files: false
        shutdown_vm: false
        run: |
          gmake -j$(sysctl -n hw.ncpu) STRICT=1 VERBOSE=1 AUTO_DEPS=1
    - name: Test
      uses: cross-platform-actions/action@v0.22.0
      with:
        architecture: x86_64
        hypervisor: xhyve
        memory: 4G
        operating_system: openbsd
        version: '7.4'
        shell: bash
        sync_files: false
        shutdown_vm: false
        run: |
          gmake -j$(sysctl -n hw.ncpu) STRICT=1 VERBOSE=1 AUTO_DEPS=1 check
    - name: Shutdown VM
      uses: cross-platform-actions/action@v0.22.0
      with:
        architecture: x86_64
        hypervisor: xhyve
        memory: 4G
        operating_system: openbsd
        version: '7.4'
        shell: bash
        sync_files: false
        shutdown_vm: true
        run: true
