name: OpenBSD 7.4 Makefile

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
    - uses: cross-platform-actions/action@v0.21.1
      with:
        architecture: x86_64
        hypervisor: qemu
        memory: 4G
        operating_system: openbsd
        version: '7.4'
        sync_files: runner-to-vm
        shell: bash
        run: |
          sudo pkg_add subversion p5-XML-XPath git mawk gmake pkgconf autoconf autoconf-archive automake libtool libltdl help2man doxygen mpg123 libogg libvorbis flac libsndfile pulseaudio portaudio-svn sdl2
          gmake -j$(sysctl -n hw.ncpu) STRICT=1 VERBOSE=1 AUTO_DEPS=1
          gmake -j$(sysctl -n hw.ncpu) STRICT=1 VERBOSE=1 AUTO_DEPS=1 check
